import '$ui/icons/go-network'
import '$ui/icons/go-circle'
import '$ui/icons/go-connect'
import '$ui/icons/go-excel'
import '$ui/icons/go-far'
import '$ui/icons/go-grid'
import '$ui/icons/go-hide'
import '$ui/icons/go-image'
import '$ui/icons/go-invert'
import '$ui/icons/go-json'
import '$ui/icons/go-lock'
import '$ui/icons/go-near'
import '$ui/icons/go-org'
import '$ui/icons/go-redo'
import '$ui/icons/go-search'
import '$ui/icons/go-select'
import '$ui/icons/go-show-all'
import '$ui/icons/go-undo'
import '$ui/icons/go-unlock'
import '$ui/icons/go-view'
import '$ui/icons/go-visible'
import '$ui/icons/go-zoom-in'
import '$ui/icons/go-zoom-out'



